updated travis.yaml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,15 +1,26 @@
 language: minimal
 services:
     - docker
-stages:
-  - name: deploy
-    if: branch == main AND type = push
-jobs:
-  include:
-    - stage: deploy
-      script:
-        - echo "$ARTIFACT_REGISTRY_KEY" | docker login -u _json_key_base64 --password-stdin https://us-west1-docker.pkg.dev
-        - export THIRD_PARTY_REPO=us-west1-docker.pkg.dev/som-rit-infrastructure-prod/third-party/prod-dev-compare
-        - docker build -f Dockerfile -t $THIRD_PARTY_REPO:build-$TRAVIS_BUILD_NUMBER -t $THIRD_PARTY_REPO:latest .
-        - docker push $THIRD_PARTY_REPO:build-$TRAVIS_BUILD_NUMBER
-        - docker push $THIRD_PARTY_REPO:latest
+
+before_install:
+  # Stop Travis immediately when any build command fails so it is easier to find the problem
+  - set -eo pipefail
+  # Add Google as a Docker mirror because Docker Hub download quotas cause build failures
+  - tmpdaemon=$(mktemp)
+  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > $tmpdaemon
+  - sudo mv $tmpdaemon /etc/docker/daemon.json
+  - sudo systemctl daemon-reload
+  - sudo systemctl restart docker
+  - docker system info
+
+script:
+  - export THIRD_PARTY_REPO=us-west1-docker.pkg.dev/som-rit-infrastructure-prod/third-party/prod-dev-compare
+  - docker build -f Dockerfile -t $THIRD_PARTY_REPO:build-$TRAVIS_BUILD_NUMBER -t $THIRD_PARTY_REPO:latest .
+
+after_success:
+  # Push Docker images for regular (not cron) main builds (credentials are only available on main)
+  - if [ -n "$ARTIFACT_REGISTRY_KEY" ] && [ "$TRAVIS_EVENT_TYPE" = "push" ]; then
+      echo "$ARTIFACT_REGISTRY_KEY" | docker login -u _json_key_base64 --password-stdin https://us-west1-docker.pkg.dev;
+      docker push $THIRD_PARTY_REPO:build-$TRAVIS_BUILD_NUMBER;
+      docker push $THIRD_PARTY_REPO:latest;
+    fi
